@startuml
(*)  --> "Страница Тесты"


"Страница Тесты" --> "Запрос на сервера (1)"


if "Пользователь нашел тест?" then
    -->[нет] "Выбор категории Теста"
else
    -->[да] "Выбор теста"
endif

"Выбор категории Теста" --> "Выбор конкретного теста"
"Выбор конкретного теста" --> "Информация о тесте"
"Выбор теста" --> "Информация о тесте"

if "Пользователь собирается проходить выбранный тест?" then
    -->[нет] "Страница Тесты"
else
    -->[да] "Прохождение теста"
endif

"Прохождение теста" --> "Выбор ответов"
"Выбор ответов" --> "Переход к следующему вопросу или к предыдущему"

if "Есть ли еще вопросы?" then
    --> [нет] "Завершение теста"
else
    --> [да] "Выбор ответов"
endif

"Завершение теста" --> "Проверка результатов"
"Проверка результатов" --> "Отображение результатов"

"Отображение результатов" --> (*)

@enduml
